# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://travelingengineer.com
title: Traveling Engineer
email: sara_at_travelingengineer.com
author: Sara Hohenshelt
description: > # "Traveling the World for Engineering"
#banner_image: DSC_0040.JPG

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
